<a href="https://colab.research.google.com/github/ritwikvulli7/FML/blob/main/FML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
b = np.array([[1,2,3],[4,5,6]])
print(b)


[[1 2 3]
 [4 5 6]]
