<a href="https://colab.research.google.com/github/ritwikvulli7/FML/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.array([100])
print(a)

[100]


In [3]:
a=np.array([300])
print(a)

[300]


In [4]:
d=np.array([400])
print(d)

[400]


In [5]:
a=np.array([100,200,300])
print(a)

[100 200 300]


In [6]:
b=np.array([300,400,500])
print(b)

[300 400 500]


In [7]:
c=np.array([500,600,700])
print(c)

[500 600 700]


In [8]:
d=np.array([199,400,600])
print(d)

[199 400 600]


In [9]:
a=np.array([[100,200],[400,300]])
print(a)

[[100 200]
 [400 300]]


In [10]:
b=np.array([[30,400],[400,500]])
print(b)

[[ 30 400]
 [400 500]]


In [11]:
c=np.array([[10,20],[30,40]])
print(c)

[[10 20]
 [30 40]]


In [12]:
a=np.array([[[100,200],[300,400]],[[500,600],[700,800]]])
print(a)

[[[100 200]
  [300 400]]

 [[500 600]
  [700 800]]]


In [13]:
b=np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
print(b)

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


In [14]:
c=np.array([[[5,15],[25,35]],[[45,55],[65,75]]])
print(c)

[[[ 5 15]
  [25 35]]

 [[45 55]
  [65 75]]]


# **Asarray**

In [15]:
a=[200,300,400,500]
b=np.asarray(a,dtype=float)
print(b)

[200. 300. 400. 500.]


In [16]:
a=[1,2,3,4]
b=np.asarray(a,dtype=int)
print(b)

[1 2 3 4]


In [17]:
a=[40,50,60]
b=np.asarray(a,dtype=int)
print(b)

[40 50 60]


In [18]:
a=[[100,200],[300,400]]
b=np.asarray(a,order="c")
print(a)
for i in np.nditer(b):
  print(i)

[[100, 200], [300, 400]]
100
200
300
400


In [19]:
a=[[100,200],[300,400]]
b=np.asarray(a,order="c")
print(a)
for i in np.nditer(b):
  print(i)

[[100, 200], [300, 400]]
100
200
300
400


In [20]:
a=[[10,20],[30,40]]
b=np.asarray(a,order="F")
print(a)
for i in np.nditer(b):
   print(i)

[[10, 20], [30, 40]]
10
30
20
40


# **From Buffer**

In [22]:
a=b"SECOND YEAR CSE STUDENTS"
np.frombuffer(a,dtype='S1')

array([b'S', b'E', b'C', b'O', b'N', b'D', b' ', b'Y', b'E', b'A', b'R',
       b' ', b'C', b'S', b'E', b' ', b'S', b'T', b'U', b'D', b'E', b'N',
       b'T', b'S'], dtype='|S1')

In [23]:
a=b"RITWIK"
np.frombuffer(a,dtype='S1')

array([b'R', b'I', b'T', b'W', b'I', b'K'], dtype='|S1')

# **Count**

In [25]:
a=b"SECOND YEAR CSE STUDENTS"
np.frombuffer(a,dtype="S1",count=15)


array([b'S', b'E', b'C', b'O', b'N', b'D', b' ', b'Y', b'E', b'A', b'R',
       b' ', b'C', b'S', b'E'], dtype='|S1')

In [26]:
a=b"SECOND YEAR CSE STUDENTS"
np.frombuffer(a,dtype="S1",count=15)

array([b'S', b'E', b'C', b'O', b'N', b'D', b' ', b'Y', b'E', b'A', b'R',
       b' ', b'C', b'S', b'E'], dtype='|S1')

# **Offset**